// AUTO-GENERATED by scripts/generate-detectors.mjs from rules/extra.json.
// Do not edit by hand — change the rules file and re-run `npm run gen`.
import type { Detector } from '../types.js'
import { matchAll } from './_util.js'

const RE_0 = new RegExp("\\b[0-9a-f]{32}-us\\d{1,2}\\b", "g")
const RE_1 = new RegExp("\\bkey-[0-9a-zA-Z]{32}\\b", "g")
const RE_2 = new RegExp("\\bNRAK-[A-Z0-9]{27}\\b", "g")
const RE_3 = new RegExp("\\bpypi-AgEI[A-Za-z0-9_-]{50,}\\b", "g")
const RE_4 = new RegExp("\\bdp\\.pt\\.[A-Za-z0-9]{43}\\b", "g")
const RE_5 = new RegExp("\\bglsa_[A-Za-z0-9]{32}_[a-f0-9]{8}\\b", "g")
const RE_6 = new RegExp("\\bdapi[0-9a-f]{32}\\b", "g")
const RE_7 = new RegExp("\\b\\d{8,10}:[A-Za-z0-9_-]{35}\\b", "g")
const RE_8 = new RegExp("\\bxkeysib-[a-f0-9]{64}-[A-Za-z0-9]{16}\\b", "g")
const RE_9 = new RegExp("\\bpscale_tkn_[A-Za-z0-9_-]{32,}\\b", "g")
const RE_10 = new RegExp("\\bsk-or-v1-[0-9a-f]{40,}\\b", "g")
const RE_11 = new RegExp("\\bgsk_[A-Za-z0-9]{52}\\b", "g")
const RE_12 = new RegExp("\\bpplx-[A-Za-z0-9]{40,}\\b", "g")
const RE_13 = new RegExp("\\br8_[A-Za-z0-9]{37}\\b", "g")
const RE_14 = new RegExp("\\bntn_[0-9A-Za-z]{40,}\\b", "g")
const RE_15 = new RegExp("\\b[MNO][A-Za-z0-9_-]{23,25}\\.[A-Za-z0-9_-]{6}\\.[A-Za-z0-9_-]{27,38}\\b", "g")
const RE_16 = new RegExp("\\bfigd_[0-9A-Za-z_.-]{40,}\\b", "g")
const RE_17 = new RegExp("\\bpat[0-9A-Za-z]{14}\\.[0-9A-Za-z_-]{40,}\\b", "g")
const RE_18 = new RegExp("\\b[A-Za-z0-9]{14}\\.atlasv1\\.[A-Za-z0-9_-]{60,}\\b", "g")
const RE_19 = new RegExp("\\bsl\\.[A-Za-z0-9_-]{130,}\\b", "g")
const RE_20 = new RegExp("\\bxai-[A-Za-z0-9]{80}\\b", "g")
const RE_21 = new RegExp("\\bFLWSECK[_-][0-9A-Za-z-]{20,}\\b", "g")
const RE_22 = new RegExp("\\brzp_(?:live|test)_[0-9A-Za-z]{14,}\\b", "g")
const RE_23 = new RegExp("\\bfw_[0-9A-Za-z]{24,}\\b", "g")
const RE_24 = new RegExp("\\bATATT3x[A-Za-z0-9_=+/.-]{150,}\\b", "g")
const RE_25 = new RegExp("\\btskey-(?:auth|api|client)-[A-Za-z0-9]{10,}-[A-Za-z0-9]{20,}\\b", "g")
const RE_26 = new RegExp("\\bre_(?=[A-Za-z0-9_]*\\d)[A-Za-z0-9_]{22,}\\b", "g")
const RE_27 = new RegExp("\\bhvs\\.[A-Za-z0-9._-]{90,120}\\b", "g")
const RE_28 = new RegExp("\\bdt0c01\\.[A-Za-z0-9_]{24}\\.[A-Za-z0-9_]{64}\\b", "g")
const RE_29 = new RegExp("\\btfp_[A-Za-z0-9._=-]{59}", "g")
const RE_30 = new RegExp("\\bpnu_[A-Za-z0-9_]{36}\\b", "g")
const RE_31 = new RegExp("\\brubygems_[a-f0-9_]{48}\\b", "g")
const RE_32 = new RegExp("\\bCLOJARS_[A-Za-z0-9_]{60}\\b", "g")
const RE_33 = new RegExp("\\bduffel_(?:test|live)_[A-Za-z0-9._=-]{43}", "g")
const RE_34 = new RegExp("\\bfio-u-[A-Za-z0-9._=-]{64}", "g")
const RE_35 = new RegExp("\\bshippo_(?:live|test)_[a-fA-F0-9_]{40}\\b", "g")
const RE_36 = new RegExp("\\bEZAK[A-Za-z0-9_]{54}\\b", "g")
const RE_37 = new RegExp("\\bLTAI[A-Za-z0-9_]{20}\\b", "g")
const RE_38 = new RegExp("\\bAGE-SECRET-KEY-1[QPZRY9X8GF2TVDW0S3JN54KHCE6MUA7L_]{58}\\b", "g")
const RE_39 = new RegExp("\\brdme_[a-z0-9_]{70}\\b", "g")
const RE_40 = new RegExp("\\bs-s4t2(?:ud|af)-[a-f0-9_]{64}\\b", "g")
const RE_41 = new RegExp("\\bEAA[MC][A-Za-z0-9_]{100,}\\b", "g")
const RE_42 = new RegExp("\\bsntryu_[a-f0-9_]{64}\\b", "g")
const RE_43 = new RegExp("\\b[5KL][1-9A-HJ-NP-Za-km-z]{50,51}\\b", "g")
const RE_44 = new RegExp("\\b9\\d{2}-[5-9]\\d-\\d{4}\\b", "g")
const RE_45 = new RegExp("\\b0x[a-fA-F0-9]{40}\\b", "g")
const RE_46 = new RegExp("\\bbc1[a-z0-9]{25,39}\\b", "g")
const RE_47 = new RegExp("\\+[1-9]\\d{7,14}\\b", "g")
const RE_48 = new RegExp("\\b[A-Z]{3}[ABCFGHLJPT][A-Z]\\d{4}[A-Z]\\b", "g")
const RE_49 = new RegExp("\\b[A-CEGHJ-PR-TW-Z][A-CEGHJ-NPR-TW-Z]\\d{6}[A-D]\\b", "g")

export const generated: Detector[] = [
  {
    id: "mailchimp_key",
    label: "Mailchimp API key",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_0, text),
    fixtures: { positives: ["aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-us1","ffffffffffffffffffffffffffffffff-us20"], negatives: ["abcd-us1","aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-usX","not a mailchimp key"] },
  },
  {
    id: "mailgun_key",
    label: "Mailgun API key",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_1, text),
    fixtures: { positives: ["key-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","key-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"], negatives: ["key-tooshort","a keyword here","key-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"] },
  },
  {
    id: "newrelic_key",
    label: "New Relic user key",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_2, text),
    fixtures: { positives: ["NRAK-AAAAAAAAAAAAAAAAAAAAAAAAAAA","NRAK-000000000000000000000000000"], negatives: ["NRAK-short","nrak-AAAAAAAAAAAAAAAAAAAAAAAAAAA","just some text"] },
  },
  {
    id: "pypi_token",
    label: "PyPI upload token",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_3, text),
    fixtures: { positives: ["pypi-AgEIaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","pypi-AgEIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"], negatives: ["pypi-short","pypi-XXXXaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","a pypi package"] },
  },
  {
    id: "doppler_token",
    label: "Doppler personal token",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_4, text),
    fixtures: { positives: ["dp.pt.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","dp.pt.AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"], negatives: ["dp.pt.short","dp.sa.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","doppler config"] },
  },
  {
    id: "grafana_token",
    label: "Grafana service account token",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_5, text),
    fixtures: { positives: ["glsa_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa_00000000","glsa_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA_ffffffff"], negatives: ["glsa_short","glsa_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa_xyz","grafana dashboard"] },
  },
  {
    id: "databricks_token",
    label: "Databricks token",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_6, text),
    fixtures: { positives: ["dapiaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","dapi00000000000000000000000000000000"], negatives: ["dapishort","dapigggggggggggggggggggggggggggggggg","a databricks notebook"] },
  },
  {
    id: "telegram_bot_token",
    label: "Telegram bot token",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_7, text),
    fixtures: { positives: ["111111111:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","0000000000:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"], negatives: ["123:abc","111111111:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","a telegram message"] },
  },
  {
    id: "brevo_key",
    label: "Brevo (Sendinblue) API key",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_8, text),
    fixtures: { positives: ["xkeysib-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-AAAAAAAAAAAAAAAA","xkeysib-0000000000000000000000000000000000000000000000000000000000000000-bbbbbbbbbbbbbbbb"], negatives: ["xkeysib-short","xkeysib-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-short","a brevo email"] },
  },
  {
    id: "planetscale_token",
    label: "PlanetScale password token",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_9, text),
    fixtures: { positives: ["pscale_tkn_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","pscale_tkn_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"], negatives: ["pscale_tkn_short","pscale_pw_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","a planetscale db"] },
  },
  {
    id: "openrouter_key",
    label: "OpenRouter API key",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_10, text),
    fixtures: { positives: ["sk-or-v1-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","sk-or-v1-00000000000000000000000000000000000000000000000000"], negatives: ["sk-or-v1-short","sk-or-v2-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","an openrouter model"] },
  },
  {
    id: "groq_key",
    label: "Groq API key",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_11, text),
    fixtures: { positives: ["gsk_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","gsk_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"], negatives: ["gsk_short","gsk_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","a groq request"] },
  },
  {
    id: "perplexity_key",
    label: "Perplexity API key",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_12, text),
    fixtures: { positives: ["pplx-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","pplx-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"], negatives: ["pplx-short","pplx-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","a perplexity search"] },
  },
  {
    id: "replicate_token",
    label: "Replicate API token",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_13, text),
    fixtures: { positives: ["r8_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","r8_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"], negatives: ["r8_short","r8_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","a replicate model"] },
  },
  {
    id: "notion_token",
    label: "Notion integration token",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_14, text),
    fixtures: { positives: ["ntn_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","ntn_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"], negatives: ["ntn_short","ntn_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","a notion page"] },
  },
  {
    id: "discord_bot_token",
    label: "Discord bot token",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_15, text),
    fixtures: { positives: ["Maaaaaaaaaaaaaaaaaaaaaaa.aaaaaa.aaaaaaaaaaaaaaaaaaaaaaaaaaa","NAAAAAAAAAAAAAAAAAAAAAAAAA.AAAAAA.AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"], negatives: ["Maaaaaaaaaa.aaaaaa.aaaaaaaaaaaaaaaaaaaaaaaaaaa","Xaaaaaaaaaaaaaaaaaaaaaaa.aaaaaa.aaaaaaaaaaaaaaaaaaaaaaaaaaa","a discord server"] },
  },
  {
    id: "figma_token",
    label: "Figma personal access token",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_16, text),
    fixtures: { positives: ["figd_aaaaaaaaaaaaaaaaaaaa.bbbbbbbbbbbbbbbbbbbb","figd_AAAAAAAAAAAAAAAAAAAAAAAA.BBBBBBBBBBBBBBBBBBBBBBBB"], negatives: ["figd_short","figx_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","a figma file"] },
  },
  {
    id: "airtable_pat",
    label: "Airtable personal access token",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_17, text),
    fixtures: { positives: ["pataaaaaaaaaaaaaa.bbbbbbbbbbbbbbbbbbbb-cccccccccccccccccccc","patAAAAAAAAAAAAAA.00000000000000000000_11111111111111111111"], negatives: ["pataaaaaaaaaaaaaa.short","patshort","a patch file"] },
  },
  {
    id: "terraform_cloud_token",
    label: "Terraform Cloud API token",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_18, text),
    fixtures: { positives: ["aaaaaaaaaaaaaa.atlasv1.bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb","AAAAAAAAAAAAAA.atlasv1.0000000000000000000000000000000000000000000000000000000000000000000000"], negatives: ["aaaaaaaaaaaaaa.atlasv2.bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb","short.atlasv1.short","a terraform plan"] },
  },
  {
    id: "dropbox_token",
    label: "Dropbox access token",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_19, text),
    fixtures: { positives: ["sl.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","sl.AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"], negatives: ["sl.short","sl_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","a slack message"] },
  },
  {
    id: "xai_key",
    label: "xAI (Grok) API key",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_20, text),
    fixtures: { positives: ["xai-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","xai-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"], negatives: ["xai-short","xai-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","an xai model"] },
  },
  {
    id: "flutterwave_secret",
    label: "Flutterwave secret key",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_21, text),
    fixtures: { positives: ["FLWSECK-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","FLWSECK_TEST-AAAAAAAAAAAAAAAAAAAAAAAA"], negatives: ["FLWSECK-short","FLWPUBK-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","a flutterwave payment"] },
  },
  {
    id: "razorpay_key",
    label: "Razorpay API key",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_22, text),
    fixtures: { positives: ["rzp_live_aaaaaaaaaaaaaa","rzp_test_AAAAAAAAAAAAAAAAAA"], negatives: ["rzp_live_short","rzp_prod_aaaaaaaaaaaaaa","a razorpay order"] },
  },
  {
    id: "fireworks_key",
    label: "Fireworks AI API key",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_23, text),
    fixtures: { positives: ["fw_aaaaaaaaaaaaaaaaaaaaaaaa","fw_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"], negatives: ["fw_short","fwd_aaaaaaaaaaaaaaaaaaaaaaaa","a firmware update"] },
  },
  {
    id: "atlassian_token",
    label: "Atlassian API token",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_24, text),
    fixtures: { positives: ["ATATT3xFfGF0aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","ATATT3xAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"], negatives: ["ATATT3x_short","ATATTshort","an atlassian ticket"] },
  },
  {
    id: "tailscale_key",
    label: "Tailscale auth key",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_25, text),
    fixtures: { positives: ["tskey-auth-aaaaaaaaaaaa-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb","tskey-api-AAAAAAAAAAAAAAAA-000000000000000000000000000000"], negatives: ["tskey-auth-short","tskey-xxxx-aaaaaaaaaaaa-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb","a tailscale node"] },
  },
  {
    id: "resend_key",
    label: "Resend API key",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_26, text),
    fixtures: { positives: ["re_aaaaaaaaaa1aaaaaaaaaaaa","re_bbbbbbbbbbbb2bbbbbbbbbbbb"], negatives: ["re_render_component_wrapper_factory","re_short","a resend email"] },
  },
  {
    id: "hashicorp_vault_token",
    label: "HashiCorp Vault service token",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_27, text),
    fixtures: { positives: ["hvs.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","hvs.bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb.bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"], negatives: ["hvs.short","hvx.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","a vault token"] },
  },
  {
    id: "dynatrace_token",
    label: "Dynatrace API token",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_28, text),
    fixtures: { positives: ["dt0c01.aaaaaaaaaaa_aaaaaaaaaaaa.bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb_bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb","dt0c01.ccccccccccc_cccccccccccc.ddddddddddddddddddddddddddddddd_dddddddddddddddddddddddddddddddd"], negatives: ["dt0c01.aaaaaaaaaaaaaaaaaaaaaaaa.short","dt0c02.aaaaaaaaaaa_aaaaaaaaaaaa.bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb_bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb","a dynatrace token"] },
  },
  {
    id: "typeform_token",
    label: "Typeform API token",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_29, text),
    fixtures: { positives: ["tfp_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA","tfp_BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"], negatives: ["tfp_short","tfx_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA","a typeform survey"] },
  },
  {
    id: "prefect_token",
    label: "Prefect API token",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_30, text),
    fixtures: { positives: ["pnu_aaaaaaaaaaaaaaaaa_aaaaaaaaaaaaaaaaaa","pnu_bbbbbbbbbbbbbbbbb_bbbbbbbbbbbbbbbbbb"], negatives: ["pnu_short","pnx_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","a prefect flow"] },
  },
  {
    id: "rubygems_token",
    label: "RubyGems API token",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_31, text),
    fixtures: { positives: ["rubygems_aaaaaaaaaaaaaaaaaaaaaaa_aaaaaaaaaaaaaaaaaaaaaaaa","rubygems_bbbbbbbbbbbbbbbbbbbbbbb_bbbbbbbbbbbbbbbbbbbbbbbb"], negatives: ["rubygems_short","rubygemx_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","a ruby gem"] },
  },
  {
    id: "clojars_token",
    label: "Clojars API token",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_32, text),
    fixtures: { positives: ["CLOJARS_aaaaaaaaaaaaaaaaaaaaaaaaaaaaa_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","CLOJARS_bbbbbbbbbbbbbbbbbbbbbbbbbbbbb_bbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"], negatives: ["CLOJARS_short","CLOJARX_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","a clojure lib"] },
  },
  {
    id: "duffel_token",
    label: "Duffel API token",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_33, text),
    fixtures: { positives: ["duffel_test_aaaaaaaaaaaaaaaaaaaaa.aaaaaaaaaaaaaaaaaaaaa","duffel_live_bbbbbbbbbbbbbbbbbbbbb.bbbbbbbbbbbbbbbbbbbbb"], negatives: ["duffel_test_short","duffel_prod_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","a duffel booking"] },
  },
  {
    id: "frameio_token",
    label: "Frame.io API token",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_34, text),
    fixtures: { positives: ["fio-u-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","fio-u-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb.bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"], negatives: ["fio-u-short","fio-x-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","a frame io asset"] },
  },
  {
    id: "shippo_token",
    label: "Shippo API token",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_35, text),
    fixtures: { positives: ["shippo_live_aaaaaaaaaaaaaaaaaaa_aaaaaaaaaaaaaaaaaaaa","shippo_test_bbbbbbbbbbbbbbbbbbb_bbbbbbbbbbbbbbbbbbbb"], negatives: ["shippo_live_short","shippo_prod_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","a shippo label"] },
  },
  {
    id: "easypost_token",
    label: "EasyPost API token",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_36, text),
    fixtures: { positives: ["EZAKaaaaaaaaaaaaaaaaaaaaaaaaaa_aaaaaaaaaaaaaaaaaaaaaaaaaaa","EZAKbbbbbbbbbbbbbbbbbbbbbbbbbb_bbbbbbbbbbbbbbbbbbbbbbbbbbb"], negatives: ["EZAKshort","EZAXaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","an easypost shipment"] },
  },
  {
    id: "alibaba_access_key",
    label: "Alibaba Cloud AccessKey ID",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_37, text),
    fixtures: { positives: ["LTAIaaaaaaaaa_aaaaaaaaaa","LTAIbbbbbbbbb_bbbbbbbbbb"], negatives: ["LTAIshort","LTAXaaaaaaaaaaaaaaaaaaaa","an alibaba account"] },
  },
  {
    id: "age_secret_key",
    label: "age secret key",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_38, text),
    fixtures: { positives: ["AGE-SECRET-KEY-1QQQQQQQQQQQQQQQQQQQQQQQQQQQQ_QQQQQQQQQQQQQQQQQQQQQQQQQQQQQ","AGE-SECRET-KEY-1AAAAAAAAAAAAAAAAAAAAAAAAAAAA_AAAAAAAAAAAAAAAAAAAAAAAAAAAAA"], negatives: ["AGE-SECRET-KEY-1QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ","AGE-PUBLIC-KEY-1QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ","an age identity"] },
  },
  {
    id: "readme_token",
    label: "ReadMe API token",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_39, text),
    fixtures: { positives: ["rdme_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","rdme_bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb_bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"], negatives: ["rdme_short","rdmx_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","a readme file"] },
  },
  {
    id: "intra42_secret",
    label: "Intra42 client secret",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_40, text),
    fixtures: { positives: ["s-s4t2ud-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","s-s4t2af-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb_bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"], negatives: ["s-s4t2ud-short","s-s4t2xx-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","an intra42 app"] },
  },
  {
    id: "facebook_token",
    label: "Facebook access token",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_41, text),
    fixtures: { positives: ["EAAMaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","EAACbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb_bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"], negatives: ["EAAMaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","EAAXaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","a facebook post"] },
  },
  {
    id: "sentry_user_token",
    label: "Sentry user token",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_42, text),
    fixtures: { positives: ["sntryu_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","sntryu_bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb_bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"], negatives: ["sntryu_short","sntryx_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","a sentry issue"] },
  },
  {
    id: "bitcoin_wif_key",
    label: "Bitcoin private key (WIF)",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_43, text),
    fixtures: { positives: ["5aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","Kbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"], negatives: ["5aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","0aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","a bitcoin wallet"] },
  },
  {
    id: "us_itin",
    label: "US Individual Taxpayer Identification Number",
    severity: "warning",
    defaultEnabled: false,
    scan: (text) => matchAll(RE_44, text),
    fixtures: { positives: ["912-70-1234","999-95-6789"], negatives: ["912-40-1234","123-70-1234","an itin value"] },
  },
  {
    id: "ethereum_address",
    label: "Ethereum address",
    severity: "warning",
    defaultEnabled: false,
    scan: (text) => matchAll(RE_45, text),
    fixtures: { positives: ["0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","0xAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"], negatives: ["0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","0xgggggggggggggggggggggggggggggggggggggggg","a wallet address"] },
  },
  {
    id: "bitcoin_address",
    label: "Bitcoin address (bech32)",
    severity: "warning",
    defaultEnabled: false,
    scan: (text) => matchAll(RE_46, text),
    fixtures: { positives: ["bc1aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","bc1qqqqqqqqqqqqqqqqqqqqqqqqq"], negatives: ["bc1short","bc2aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","a bitcoin address"] },
  },
  {
    id: "phone_e164",
    label: "Phone number (E.164)",
    severity: "warning",
    defaultEnabled: false,
    scan: (text) => matchAll(RE_47, text),
    fixtures: { positives: ["+14155552671","+919876543210"], negatives: ["+0123456789","4155552671","call us anytime"] },
  },
  {
    id: "india_pan",
    label: "India PAN",
    severity: "warning",
    defaultEnabled: false,
    scan: (text) => matchAll(RE_48, text),
    fixtures: { positives: ["ABCPE1234F","AAAPA0000A"], negatives: ["ABCDE1234F","ABCPE12345","a pan card"] },
  },
  {
    id: "uk_nino",
    label: "UK National Insurance number",
    severity: "warning",
    defaultEnabled: false,
    scan: (text) => matchAll(RE_49, text),
    fixtures: { positives: ["AB123456C","JG567890A"], negatives: ["DA123456C","AB123456E","a nino value"] },
  },
]
