// AUTO-GENERATED by scripts/generate-detectors.mjs from rules/extra.json.
// Do not edit by hand — change the rules file and re-run `npm run gen`.
import type { Detector } from '../types.js'
import { matchAll } from './_util.js'

const RE_0 = new RegExp("\\b[0-9a-f]{32}-us\\d{1,2}\\b", "g")
const RE_1 = new RegExp("\\bkey-[0-9a-zA-Z]{32}\\b", "g")
const RE_2 = new RegExp("\\bNRAK-[A-Z0-9]{27}\\b", "g")
const RE_3 = new RegExp("\\bpypi-AgEI[A-Za-z0-9_-]{50,}\\b", "g")
const RE_4 = new RegExp("\\bdp\\.pt\\.[A-Za-z0-9]{43}\\b", "g")
const RE_5 = new RegExp("\\bglsa_[A-Za-z0-9]{32}_[a-f0-9]{8}\\b", "g")
const RE_6 = new RegExp("\\bdapi[0-9a-f]{32}\\b", "g")
const RE_7 = new RegExp("\\b\\d{8,10}:[A-Za-z0-9_-]{35}\\b", "g")
const RE_8 = new RegExp("\\bxkeysib-[a-f0-9]{64}-[A-Za-z0-9]{16}\\b", "g")
const RE_9 = new RegExp("\\bpscale_tkn_[A-Za-z0-9_-]{32,}\\b", "g")

export const generated: Detector[] = [
  {
    id: "mailchimp_key",
    label: "Mailchimp API key",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_0, text),
    fixtures: { positives: ["aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-us1","ffffffffffffffffffffffffffffffff-us20"], negatives: ["abcd-us1","aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-usX","not a mailchimp key"] },
  },
  {
    id: "mailgun_key",
    label: "Mailgun API key",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_1, text),
    fixtures: { positives: ["key-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","key-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"], negatives: ["key-tooshort","a keyword here","key-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"] },
  },
  {
    id: "newrelic_key",
    label: "New Relic user key",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_2, text),
    fixtures: { positives: ["NRAK-AAAAAAAAAAAAAAAAAAAAAAAAAAA","NRAK-000000000000000000000000000"], negatives: ["NRAK-short","nrak-AAAAAAAAAAAAAAAAAAAAAAAAAAA","just some text"] },
  },
  {
    id: "pypi_token",
    label: "PyPI upload token",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_3, text),
    fixtures: { positives: ["pypi-AgEIaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","pypi-AgEIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"], negatives: ["pypi-short","pypi-XXXXaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","a pypi package"] },
  },
  {
    id: "doppler_token",
    label: "Doppler personal token",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_4, text),
    fixtures: { positives: ["dp.pt.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","dp.pt.AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"], negatives: ["dp.pt.short","dp.sa.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","doppler config"] },
  },
  {
    id: "grafana_token",
    label: "Grafana service account token",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_5, text),
    fixtures: { positives: ["glsa_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa_00000000","glsa_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA_ffffffff"], negatives: ["glsa_short","glsa_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa_xyz","grafana dashboard"] },
  },
  {
    id: "databricks_token",
    label: "Databricks token",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_6, text),
    fixtures: { positives: ["dapiaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","dapi00000000000000000000000000000000"], negatives: ["dapishort","dapigggggggggggggggggggggggggggggggg","a databricks notebook"] },
  },
  {
    id: "telegram_bot_token",
    label: "Telegram bot token",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_7, text),
    fixtures: { positives: ["111111111:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","0000000000:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"], negatives: ["123:abc","111111111:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","a telegram message"] },
  },
  {
    id: "brevo_key",
    label: "Brevo (Sendinblue) API key",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_8, text),
    fixtures: { positives: ["xkeysib-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-AAAAAAAAAAAAAAAA","xkeysib-0000000000000000000000000000000000000000000000000000000000000000-bbbbbbbbbbbbbbbb"], negatives: ["xkeysib-short","xkeysib-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-short","a brevo email"] },
  },
  {
    id: "planetscale_token",
    label: "PlanetScale password token",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_9, text),
    fixtures: { positives: ["pscale_tkn_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","pscale_tkn_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"], negatives: ["pscale_tkn_short","pscale_pw_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","a planetscale db"] },
  },
]
