// AUTO-GENERATED by scripts/generate-detectors.mjs from rules/extra.json.
// Do not edit by hand — change the rules file and re-run `npm run gen`.
import type { Detector } from '../types.js'
import { matchAll } from './_util.js'

const RE_0 = new RegExp("\\b[0-9a-f]{32}-us\\d{1,2}\\b", "g")
const RE_1 = new RegExp("\\bkey-[0-9a-zA-Z]{32}\\b", "g")
const RE_2 = new RegExp("\\bNRAK-[A-Z0-9]{27}\\b", "g")
const RE_3 = new RegExp("\\bpypi-AgEI[A-Za-z0-9_-]{50,}\\b", "g")
const RE_4 = new RegExp("\\bdp\\.pt\\.[A-Za-z0-9]{43}\\b", "g")
const RE_5 = new RegExp("\\bglsa_[A-Za-z0-9]{32}_[a-f0-9]{8}\\b", "g")
const RE_6 = new RegExp("\\bdapi[0-9a-f]{32}\\b", "g")
const RE_7 = new RegExp("\\b\\d{8,10}:[A-Za-z0-9_-]{35}\\b", "g")
const RE_8 = new RegExp("\\bxkeysib-[a-f0-9]{64}-[A-Za-z0-9]{16}\\b", "g")
const RE_9 = new RegExp("\\bpscale_tkn_[A-Za-z0-9_-]{32,}\\b", "g")
const RE_10 = new RegExp("\\bsk-or-v1-[0-9a-f]{40,}\\b", "g")
const RE_11 = new RegExp("\\bgsk_[A-Za-z0-9]{52}\\b", "g")
const RE_12 = new RegExp("\\bpplx-[A-Za-z0-9]{40,}\\b", "g")
const RE_13 = new RegExp("\\br8_[A-Za-z0-9]{37}\\b", "g")
const RE_14 = new RegExp("\\bntn_[0-9A-Za-z]{40,}\\b", "g")
const RE_15 = new RegExp("\\b[MNO][A-Za-z0-9_-]{23,25}\\.[A-Za-z0-9_-]{6}\\.[A-Za-z0-9_-]{27,38}\\b", "g")

export const generated: Detector[] = [
  {
    id: "mailchimp_key",
    label: "Mailchimp API key",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_0, text),
    fixtures: { positives: ["aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-us1","ffffffffffffffffffffffffffffffff-us20"], negatives: ["abcd-us1","aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-usX","not a mailchimp key"] },
  },
  {
    id: "mailgun_key",
    label: "Mailgun API key",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_1, text),
    fixtures: { positives: ["key-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","key-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"], negatives: ["key-tooshort","a keyword here","key-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"] },
  },
  {
    id: "newrelic_key",
    label: "New Relic user key",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_2, text),
    fixtures: { positives: ["NRAK-AAAAAAAAAAAAAAAAAAAAAAAAAAA","NRAK-000000000000000000000000000"], negatives: ["NRAK-short","nrak-AAAAAAAAAAAAAAAAAAAAAAAAAAA","just some text"] },
  },
  {
    id: "pypi_token",
    label: "PyPI upload token",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_3, text),
    fixtures: { positives: ["pypi-AgEIaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","pypi-AgEIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"], negatives: ["pypi-short","pypi-XXXXaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","a pypi package"] },
  },
  {
    id: "doppler_token",
    label: "Doppler personal token",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_4, text),
    fixtures: { positives: ["dp.pt.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","dp.pt.AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"], negatives: ["dp.pt.short","dp.sa.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","doppler config"] },
  },
  {
    id: "grafana_token",
    label: "Grafana service account token",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_5, text),
    fixtures: { positives: ["glsa_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa_00000000","glsa_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA_ffffffff"], negatives: ["glsa_short","glsa_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa_xyz","grafana dashboard"] },
  },
  {
    id: "databricks_token",
    label: "Databricks token",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_6, text),
    fixtures: { positives: ["dapiaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","dapi00000000000000000000000000000000"], negatives: ["dapishort","dapigggggggggggggggggggggggggggggggg","a databricks notebook"] },
  },
  {
    id: "telegram_bot_token",
    label: "Telegram bot token",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_7, text),
    fixtures: { positives: ["111111111:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","0000000000:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"], negatives: ["123:abc","111111111:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","a telegram message"] },
  },
  {
    id: "brevo_key",
    label: "Brevo (Sendinblue) API key",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_8, text),
    fixtures: { positives: ["xkeysib-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-AAAAAAAAAAAAAAAA","xkeysib-0000000000000000000000000000000000000000000000000000000000000000-bbbbbbbbbbbbbbbb"], negatives: ["xkeysib-short","xkeysib-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-short","a brevo email"] },
  },
  {
    id: "planetscale_token",
    label: "PlanetScale password token",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_9, text),
    fixtures: { positives: ["pscale_tkn_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","pscale_tkn_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"], negatives: ["pscale_tkn_short","pscale_pw_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","a planetscale db"] },
  },
  {
    id: "openrouter_key",
    label: "OpenRouter API key",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_10, text),
    fixtures: { positives: ["sk-or-v1-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","sk-or-v1-00000000000000000000000000000000000000000000000000"], negatives: ["sk-or-v1-short","sk-or-v2-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","an openrouter model"] },
  },
  {
    id: "groq_key",
    label: "Groq API key",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_11, text),
    fixtures: { positives: ["gsk_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","gsk_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"], negatives: ["gsk_short","gsk_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","a groq request"] },
  },
  {
    id: "perplexity_key",
    label: "Perplexity API key",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_12, text),
    fixtures: { positives: ["pplx-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","pplx-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"], negatives: ["pplx-short","pplx-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","a perplexity search"] },
  },
  {
    id: "replicate_token",
    label: "Replicate API token",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_13, text),
    fixtures: { positives: ["r8_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","r8_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"], negatives: ["r8_short","r8_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","a replicate model"] },
  },
  {
    id: "notion_token",
    label: "Notion integration token",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_14, text),
    fixtures: { positives: ["ntn_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","ntn_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"], negatives: ["ntn_short","ntn_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","a notion page"] },
  },
  {
    id: "discord_bot_token",
    label: "Discord bot token",
    severity: "critical",
    defaultEnabled: true,
    scan: (text) => matchAll(RE_15, text),
    fixtures: { positives: ["Maaaaaaaaaaaaaaaaaaaaaaa.aaaaaa.aaaaaaaaaaaaaaaaaaaaaaaaaaa","NAAAAAAAAAAAAAAAAAAAAAAAAA.AAAAAA.AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"], negatives: ["Maaaaaaaaaa.aaaaaa.aaaaaaaaaaaaaaaaaaaaaaaaaaa","Xaaaaaaaaaaaaaaaaaaaaaaa.aaaaaa.aaaaaaaaaaaaaaaaaaaaaaaaaaa","a discord server"] },
  },
]
